spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME:takeone_users}?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  redis:
    host: ${REDIS_HOST:redis}
    port: 6379
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

services:
  content-service:
    url: http://content-service:8083
  job-service:
    url: http://job-service:8086

logging:
  level:
    com.takeone: INFO
